#!/bin/sh

# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local oid> <remote ref> <remote oid>
#
# This sample shows how to prevent push of commits where the log message starts
# with "WIP" (work in progress).

cd crates
cargo fmt --all -- --check  || exit 1
cargo clippy --workspace -- -D warnings || exit 1
cargo build --workspace --exclude gpu-macros || exit 1
cargo test || exit 1
RUSTFLAGS="--cfg gpu_codegen" cargo test --manifest-path rustc_codegen_gpu/Cargo.toml  || exit 1

cd ../examples
cargo fmt --all -- --check
__CODEGEN_TARGET__="GPU-CLIPPY" RUSTC=rustc cargo clippy --workspace --exclude llm-rs-gpu -- -D warnings || exit 1
cargo build  || exit 1
cargo test || exit 1