#!/usr/bin/env python3
"""Generate the agent-benchmark box plot that replaces Table 4.

Reads benchdata/all.csv and writes seguru-paper/src/fig_aibench.tex.

One box per suite, over the SeGuRu/CUDA runtime ratios of every workload and
problem size in that suite, with bounds checking enabled. Individual
measurements are overlaid and shaded by problem size within their own workload,
so the size trend (small inputs pay host-side overhead, large inputs approach
parity) is visible rather than pooled away.

KernelBench is excluded: it has no hand-written CUDA mirror, so it has no ratio.

Re-run with: python3.11 plot-aibench-fig.py
"""

import csv
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CSV = ROOT / "benchdata" / "all.csv"
OUT = ROOT.parent / "seguru-paper" / "src" / "fig_aibench.tex"

SUITES = ["aes", "heongpu", "polybench", "gpusorting"]
SUITE_TITLE = {"aes": "AES", "heongpu": "HEonGPU",
               "polybench": "PolyBench", "gpusorting": "GPUSorting"}

# onesweep is measured twice, with and without its one `unsafe` global scatter.
# The figure reports the fully safe build, so the box is not double-counted and
# every point in it comes from safe Rust. Both are in Table~\ref{tab:appendix}.
EXCLUDE_WORKLOADS = {"radix_sort_onesweep"}
RENAME = {"radix_sort_onesweep_safe": "radix_sort_onesweep"}

SIZE_CLASSES = ["small", "medium", "large"]
SIZE_COLOR = {"small": "sgSmall", "medium": "sgMed", "large": "sgLarge"}
COLOR_HTML = {"sgSmall": "C44E52", "sgMed": "DD8452", "sgLarge": "4C72B0"}
# Shape carries the size class so the figure survives greyscale printing and
# colour-blind readers; colour is only a redundant second cue.
SIZE_MARK = {"small": "*", "medium": "square*", "large": "triangle*"}
SIZE_MARK_SIZE = {"small": 1.4, "medium": 1.2, "large": 1.6}


def load():
    """SeGuRu/CUDA ratios, grouped per workload and ordered by problem size."""
    t = defaultdict(dict)
    for r in csv.DictReader(CSV.open()):
        if r["variant"] == "stock" and r["metric"] == "time":
            t[(r["suite"], r["workload"], r["parameter"])][r["implementation"]] = float(r["value"])
    per_workload = defaultdict(list)
    for (suite, wl, param), v in t.items():
        if suite in SUITES and wl not in EXCLUDE_WORKLOADS \
                and "cuda" in v and "seguru" in v:
            per_workload[(suite, RENAME.get(wl, wl))].append(
                (v["cuda"], param, v["seguru"] / v["cuda"]))
    for rows in per_workload.values():
        rows.sort()
    return per_workload


def classify(per_workload):
    """Tag each measurement with its size rank inside its own workload.

    Sizes are ranked by CUDA runtime, not by the parameter string, which is not
    comparable across suites ("1GiB" vs "ring=65536" vs "256Mi").
    """
    pts = defaultdict(list)
    for (suite, wl), rows in per_workload.items():
        n = len(rows)
        for i, (_cuda, param, ratio) in enumerate(rows):
            if i == 0:
                c = "small"
            elif i == n - 1:
                c = "large"
            else:
                c = "medium"
            pts[suite].append((ratio, c, wl, param))
    return pts


def quartiles(vals):
    """Tukey five-number summary with 1.5 IQR whiskers, as pgfplots draws it."""
    s = sorted(vals)
    n = len(s)

    def q(p):
        h = (n - 1) * p
        lo = int(h)
        hi = min(lo + 1, n - 1)
        return s[lo] + (h - lo) * (s[hi] - s[lo])

    q1, med, q3 = q(0.25), q(0.5), q(0.75)
    iqr = q3 - q1
    lo_f, hi_f = q1 - 1.5 * iqr, q3 + 1.5 * iqr
    inl = [v for v in s if lo_f <= v <= hi_f]
    out = [v for v in s if v < lo_f or v > hi_f]
    return q1, med, q3, min(inl), max(inl), out


def main():
    per_workload = load()
    pts = classify(per_workload)
    nwl = defaultdict(int)
    for suite, _wl in per_workload:
        nwl[suite] += 1

    lo = min(r for v in pts.values() for r, _, _, _ in v)
    hi = max(r for v in pts.values() for r, _, _, _ in v)

    L = []
    A = L.append
    A("% GENERATED by casestudies-by-agent-v2/plot-aibench-fig.py from benchdata/all.csv.")
    A("% Do not edit by hand: re-run ./bench-all.sh && python3.11 plot-aibench-fig.py.")
    for name, html in COLOR_HTML.items():
        A(rf"\definecolor{{{name}}}{{HTML}}{{{html}}}")
    A(r"\begin{figure}[tb]")
    A(r"\centering")
    A(r"\begin{tikzpicture}")
    A(r"\begin{axis}[")
    A(r"  width=0.99\linewidth, height=0.45\linewidth,")
    A(r"  boxplot/draw direction=y,")
    A(rf"  ymin={max(0, lo - 0.16):.2f}, ymax={hi + 0.14:.2f},")
    A(r"  ytick={0.4,0.6,0.8,1.0,1.2,1.4,1.6,1.8},")
    A(r"  ylabel={\sys{}/CUDA},")
    A(r"  ylabel near ticks,")
    A(r"  tick label style={font=\small},")
    A(r"  label style={font=\small},")
    A(r"  xtick={" + ",".join(str(i) for i in range(1, len(SUITES) + 1)) + r"},")
    A(r"  xticklabels={" + ",".join(
        rf"{{{SUITE_TITLE[s]}}}" for s in SUITES) + r"},")
    A(r"  ymajorgrids, grid style={dashed, gray!50},")
    A(r"  legend style={at={(0.5,1.02)}, anchor=south,")
    A(r"    legend columns=3, font=\small, draw=none, fill=none,")
    A(r"    /tikz/every even column/.append style={column sep=4pt}},")
    A(r"]")

    A(r"\draw[dashed,gray!75] ({rel axis cs:0,0}|-{axis cs:0,1})"
      r" -- ({rel axis cs:1,0}|-{axis cs:0,1});")

    for i, suite in enumerate(SUITES, start=1):
        vals = [r for r, _, _, _ in pts[suite]]
        q1, med, q3, wlo, whi, out = quartiles(vals)
        A(rf"% {suite}: n={len(vals)} over {nwl[suite]} workloads, median={med:.3f}")
        A(r"\addplot[boxplot prepared={"
          rf"lower whisker={wlo:.4f}, lower quartile={q1:.4f}, median={med:.4f},"
          rf" upper quartile={q3:.4f}, upper whisker={whi:.4f}, draw position={i},"
          r" box extend=0.5}, draw=black!65, fill=gray!10, thick,"
          r" mark=o, mark options={scale=0.55,draw=black!45},"
          r" forget plot] coordinates {"
          + " ".join(f"({v:.4f},0)" for v in out) + "};")

    for ci, cls in enumerate(SIZE_CLASSES):
        coords = []
        for i, suite in enumerate(SUITES, start=1):
            dx = -0.19 + 0.19 * ci
            for ratio, c, _wl, _p in pts[suite]:
                if c == cls:
                    coords.append((i + dx, ratio))
        if not coords:
            continue
        A(rf"\addplot[only marks, mark={SIZE_MARK[cls]},"
          rf" mark size={SIZE_MARK_SIZE[cls]}pt,"
          rf" draw={SIZE_COLOR[cls]}, fill={SIZE_COLOR[cls]}, opacity=0.9]"
          r" coordinates {" + " ".join(f"({x:.3f},{y:.4f})" for x, y in coords) + "};")
        A(rf"\addlegendentry{{{cls} input}}")

    A(r"\end{axis}")
    A(r"\end{tikzpicture}")
    A(r"\caption{Agent-written \sys{} kernels vs.\ CUDA C++")
    A(r"\label{fig:aibench}}")
    A(r"\end{figure}")

    OUT.write_text("\n".join(L) + "\n")
    print("wrote", OUT)
    for suite in SUITES:
        vals = [r for r, _, _, _ in pts[suite]]
        q1, med, q3, wlo, whi, out = quartiles(vals)
        print(f"  {SUITE_TITLE[suite]:<11} n={len(vals):<3} wl={nwl[suite]:<3}"
              f" median={med:.2f} IQR=[{q1:.2f},{q3:.2f}]"
              f" whisk=[{wlo:.2f},{whi:.2f}] out={[f'{o:.2f}' for o in out]}")


if __name__ == "__main__":
    main()
