#!/usr/bin/env python3
"""Generate the agent-benchmark box plot that replaces Table 4.

Reads seguru-paper/src/data/aibench.csv and writes
seguru-paper/src/figs/aibench.tex.

One box per suite, over the SeGuRu/CUDA runtime ratios of every workload and
problem size in that suite, with bounds checking enabled. Individual
measurements are overlaid and shaded by problem size within their own workload,
so the size trend (small inputs pay host-side overhead, large inputs approach
parity) is visible rather than pooled away.

Each suite also carries its geometric mean, which is the correct average for
ratios: the arithmetic mean of speedups is biased upward, since a 2x slowdown
and a 2x speedup average to 1.25 rather than 1.

Re-run with: python3.11 plot-aibench-fig.py
"""

import csv
import math
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CSV = ROOT.parent / "seguru-paper" / "src" / "data" / "aibench.csv"
OUT = ROOT.parent / "seguru-paper" / "src" / "figs" / "aibench.tex"

SUITES = ["aes", "heongpu", "polybench", "kernelbench", "gpusorting"]
SUITE_TITLE = {"aes": "AES", "heongpu": "HEonGPU",
               "polybench": "PolyBench", "kernelbench": "KernelBench",
               "gpusorting": "GPUSorting"}

# The onesweep scatter is measured twice, with and without its one `unsafe`,
# both end to end and as the binning kernel alone.
# The figure reports the fully safe build, so the box is not double-counted and
# every point in it comes from safe Rust. Both are in Table~\ref{tab:appendix}.
#
# onesweep_scan launches 4 blocks over the 256-bin global histogram, so it does
# the same work at every input size and cannot be a size-scaling measurement.

EXCLUDE_WORKLOADS = {"radix_sort_onesweep", "onesweep_digit_binning", "onesweep_scan"}
RENAME = {"radix_sort_onesweep_safe": "radix_sort_onesweep",
          "onesweep_digit_binning_safe": "onesweep_digit_binning"}

SIZE_CLASSES = ["small", "medium", "large"]
SIZE_COLOR = {"small": "sgSmall", "medium": "sgMed", "large": "sgLarge"}
COLOR_HTML = {"sgSmall": "C44E52", "sgMed": "DD8452", "sgLarge": "4C72B0",
              "sgGeo": "55A868"}
# Shape carries the size class so the figure survives greyscale printing and
# colour-blind readers; colour is only a redundant second cue.
SIZE_MARK = {"small": "*", "medium": "square*", "large": "triangle*"}
SIZE_MARK_SIZE = {"small": 1.4, "medium": 1.2, "large": 1.6}


def load():
    """Read SeGuRu/CUDA ratios from the CSV export."""
    per_workload = defaultdict(list)
    rows = (line for line in CSV.open() if not line.startswith("#"))
    for r in csv.DictReader(rows, delimiter=";"):
        if r["suite"] in SUITES and int(r["infig"]) == 1:
            per_workload[(r["suite"], r["kernel"])].append(
                (float(r["cuda"]), r["size"], float(r["ratio"])))
    for rows in per_workload.values():
        rows.sort()
    return per_workload


def classify(per_workload):
    """Tag each measurement with its size rank inside its own workload.

    Sizes are ranked by CUDA runtime, not by the parameter string, which is not
    comparable across suites ("1GiB" vs "ring=65536" vs "256Mi").
    """
    pts = defaultdict(list)
    for (suite, wl), rows in per_workload.items():
        n = len(rows)
        for i, (_cuda, param, ratio) in enumerate(rows):
            if i == 0:
                c = "small"
            elif i == n - 1:
                c = "large"
            else:
                c = "medium"
            pts[suite].append((ratio, c, wl, param))
    return pts


def gmean(vals):
    return math.exp(sum(math.log(v) for v in vals) / len(vals))


def quartiles(vals):
    """Tukey five-number summary with 1.5 IQR whiskers, as pgfplots draws it."""
    s = sorted(vals)
    n = len(s)

    def q(p):
        h = (n - 1) * p
        lo = int(h)
        hi = min(lo + 1, n - 1)
        return s[lo] + (h - lo) * (s[hi] - s[lo])

    q1, med, q3 = q(0.25), q(0.5), q(0.75)
    iqr = q3 - q1
    lo_f, hi_f = q1 - 1.5 * iqr, q3 + 1.5 * iqr
    inl = [v for v in s if lo_f <= v <= hi_f]
    out = [v for v in s if v < lo_f or v > hi_f]
    return q1, med, q3, min(inl), max(inl), out


def main():
    per_workload = load()
    pts = classify(per_workload)
    nwl = defaultdict(int)
    for suite, _wl in per_workload:
        nwl[suite] += 1

    lo = min(r for v in pts.values() for r, _, _, _ in v)
    hi = max(r for v in pts.values() for r, _, _, _ in v)

    L = []
    A = L.append
    A("% GENERATED by casestudies-by-agent-v2/plot-aibench-fig.py from data/aibench.csv.")
    A("% Do not edit by hand: re-run export-aibench-csv.py && plot-aibench-fig.py.")
    for name, html in COLOR_HTML.items():
        A(rf"\definecolor{{{name}}}{{HTML}}{{{html}}}")
    A(r"\begin{figure}[tb]")
    A(r"\centering")
    A(r"\begin{tikzpicture}")
    A(r"\begin{axis}[")
    A(r"  width=0.99\linewidth, height=0.45\linewidth,")
    A(r"  boxplot/draw direction=y,")
    A(rf"  ymin={max(0, lo - 0.16):.2f}, ymax={hi + 0.14:.2f},")
    A(r"  ytick={0.4,0.6,0.8,1.0,1.2,1.4,1.6,1.8},")
    A(r"  ylabel={\sys{}/CUDA},")
    A(r"  ylabel near ticks,")
    A(r"  tick label style={font=\small},")
    A(r"  x tick label style={font=\scriptsize},")
    A(r"  label style={font=\small},")
    A(r"  xtick={" + ",".join(str(i) for i in range(1, len(SUITES) + 1)) + r"},")
    A(r"  xticklabels={" + ",".join(
        rf"{{{SUITE_TITLE[s]}}}" for s in SUITES) + r"},")
    A(r"  ymajorgrids, grid style={dashed, gray!50},")
    A(r"  legend style={at={(0.5,1.02)}, anchor=south,")
    A(r"    legend columns=4, font=\small, draw=none, fill=none,")
    A(r"    /tikz/every even column/.append style={column sep=4pt}},")
    A(r"]")

    A(r"\draw[dashed,gray!75] ({rel axis cs:0,0}|-{axis cs:0,1})"
      r" -- ({rel axis cs:1,0}|-{axis cs:0,1});")

    for i, suite in enumerate(SUITES, start=1):
        vals = [r for r, _, _, _ in pts[suite]]
        q1, med, q3, wlo, whi, out = quartiles(vals)
        A(rf"% {suite}: n={len(vals)} over {nwl[suite]} workloads, median={med:.3f}")
        A(r"\addplot[boxplot prepared={"
          rf"lower whisker={wlo:.4f}, lower quartile={q1:.4f}, median={med:.4f},"
          rf" upper quartile={q3:.4f}, upper whisker={whi:.4f}, draw position={i},"
          r" box extend=0.35}, draw=black!65, fill=gray!10, thick,"
          r" mark=o, mark options={scale=0.55,draw=black!45},"
          r" forget plot] coordinates {"
          + " ".join(f"({v:.4f},0)" for v in out) + "};")

    for ci, cls in enumerate(SIZE_CLASSES):
        coords = []
        for i, suite in enumerate(SUITES, start=1):
            dx = -0.19 + 0.19 * ci
            for ratio, c, _wl, _p in pts[suite]:
                if c == cls:
                    coords.append((i + dx, ratio))
        if not coords:
            continue
        A(rf"\addplot[only marks, mark={SIZE_MARK[cls]},"
          rf" mark size={SIZE_MARK_SIZE[cls]}pt,"
          rf" draw={SIZE_COLOR[cls]}, fill={SIZE_COLOR[cls]}, opacity=0.9]"
          r" coordinates {" + " ".join(f"({x:.3f},{y:.4f})" for x, y in coords) + "};")
        A(rf"\addlegendentry{{{cls} input}}")

    geo = {s: gmean([r for r, _, _, _ in pts[s]]) for s in SUITES}
    A(r"\addplot[only marks, mark=diamond*, mark size=3pt, draw=black,"
      r" fill=white, line width=0.7pt] coordinates {"
      + " ".join(f"({i},{geo[s]:.4f})" for i, s in enumerate(SUITES, start=1))
      + "};")
    A(r"\end{axis}")
    A(r"\end{tikzpicture}")
    A(r"\caption{Agent-written kernels in \sys{}; lower is better.")
    A(r"\label{fig:aibench}}")
    A(r"\end{figure}")

    OUT.write_text("\n".join(L) + "\n")
    print("wrote", OUT)
    allv = [r for suite in SUITES for r, _, _, _ in pts[suite]]
    print(f"  OVERALL     n={len(allv)} geomean={gmean(allv):.4f}"
          f" min={min(allv):.3f} max={max(allv):.3f}")
    for suite in SUITES:
        vals = [r for r, _, _, _ in pts[suite]]
        q1, med, q3, wlo, whi, out = quartiles(vals)
        print(f"  {SUITE_TITLE[suite]:<11} n={len(vals):<3} wl={nwl[suite]:<3}"
              f" median={med:.2f} IQR=[{q1:.2f},{q3:.2f}]"
              f" whisk=[{wlo:.2f},{whi:.2f}] geo={gmean(vals):.3f}"
              f" out={[f'{o:.2f}' for o in out]}")


if __name__ == "__main__":
    main()
