name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest        
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache LLVM toolchain
        uses: actions/cache@v4
        with:
          path: |
            /home/linuxbrew/.linuxbrew
          key: cache-tool-${{ runner.os }}
          restore-keys: |
            cache-tool-${{ runner.os }}
      
      - name: Add NVIDIA package repository
        run: |
          sudo wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.1-1_all.deb
          sudo dpkg -i cuda-keyring_1.1-1_all.deb
          sudo apt update

      - name: Install Minimal CUDA Toolkit
        run: |
          sudo apt install -y cuda-nvcc-12-9 cuda-cuobjdump-12-9 # Or adjust version as needed
          echo "PATH=/usr/local/cuda/bin:${PATH}" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH" >> $GITHUB_ENV
      
      - name: Confirm cuda tool
        run: |
          nvcc --version
          ptxas --version
          cuobjdump --version


      - name: Install rust toolchain
        run: rustup toolchain install --profile minimal

      - name: Add rust components
        run: rustup component add --toolchain nightly-2025-03-28-x86_64-unknown-linux-gnu rustfmt rust-src clippy

      - name: Dep
        run: |
          test -x /home/linuxbrew/.linuxbrew/bin/brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          /home/linuxbrew/.linuxbrew/bin/brew install llvm@20
          /home/linuxbrew/.linuxbrew/bin/brew install binutils

      - name: Set up LLVM environment
        run: |
          LLVM_PREFIX=$(/home/linuxbrew/.linuxbrew/bin/brew --prefix llvm@20)
          BINUTILS_PREFIX=$(/home/linuxbrew/.linuxbrew/bin/brew --prefix binutils)
          echo "LLVM_PREFIX=$LLVM_PREFIX" >> $GITHUB_ENV
          echo "$LLVM_PREFIX/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=$LLVM_PREFIX/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "$BINUTILS_PREFIX/bin" >> $GITHUB_PATH

      - name: Confirm llvm version
        run: |
          which llvm-config
          llvm-config --version

      - name: Format
        working-directory: crates
        run: cargo fmt --all -- --check

      - name: Format examples
        working-directory: examples
        run: cargo fmt --all -- --check

      - name: Clippy
        working-directory: crates
        run: cargo clippy --workspace --exclude cuda_bindings -- -D warnings -C panic=abort

      - name: Clippy examples
        working-directory: examples
        run: RUSTC=rustc cargo clippy -- -D warnings -C panic=abort

      - name: Build
        working-directory: crates
        run: cargo build --workspace --exclude cuda_bindings

      - name: Run tests
        working-directory: crates/rustc_codegen_gpu
        run: cargo test

      - name: Run examples
        working-directory: examples
        run: |
          cargo build
