name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest        
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Add NVIDIA package repository
        run: |
          sudo wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.1-1_all.deb
          sudo dpkg -i cuda-keyring_1.1-1_all.deb
          sudo apt update

      - name: Install Minimal CUDA Toolkit
        run: |
          sudo apt install -y cuda-nvcc-12-9 cuda-cuobjdump-12-9 # Or adjust version as needed
          echo "PATH=/usr/local/cuda/bin:${PATH}" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH" >> $GITHUB_ENV
      
      - name: Confirm cuda tool
        run: |
          nvcc --version
          ptxas --version
          cuobjdump --version


      - name: Install rust toolchain
        run: rustup toolchain install --profile minimal

      - name: Add rust components
        run: |-
          rustup component add --toolchain nightly-2025-03-28-x86_64-unknown-linux-gnu rustfmt rust-src clippy
          rustup target add nvptx64-nvidia-cuda

      - name: Dep
        run: |
          . ./scripts/deps.sh

      - name: Set up LLVM environment
        run: |
          LLVM_PREFIX=/usr/lib/llvm-20
          echo "LLVM_PREFIX=$LLVM_PREFIX" >> $GITHUB_ENV
          echo "$LLVM_PREFIX/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=$LLVM_PREFIX/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Confirm llvm version
        run: |
          which llvm-config
          llvm-config --version

      - name: Check which folders changed
        id: check_changes
        run: |
          echo "crates_changed=false" >> $GITHUB_OUTPUT
          echo "crates_or_examples_changed=false" >> $GITHUB_OUTPUT
          if [ -n "${{ github.base_ref }}" ]; then
            BASE_REF="origin/${{ github.base_ref }}"
            git fetch origin ${{ github.base_ref }}
          else
            BASE_REF="${{ github.event.before }}"
            git fetch origin ${{ github.event.before }}
          fi
          if git diff --name-only ${BASE_REF} ${{ github.sha }} | grep -q '^crates/'; then
            echo "crates_changed=true" >> $GITHUB_OUTPUT
          fi
          if git diff --name-only ${BASE_REF} ${{ github.sha }} | grep -Eq '^(crates|examples)/'; then
            echo "crates_or_examples_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Format
        working-directory: crates
        if: ${{ steps.check_changes.outputs.crates_changed == 'true' }}
        run: cargo fmt --all -- --check

      - name: Format examples
        working-directory: examples
        if: ${{ steps.check_changes.outputs.crates_or_examples_changed == 'true' }}
        run: cargo fmt --all -- --check

      - name: Clippy
        working-directory: crates
        if: ${{ steps.check_changes.outputs.crates_changed == 'true' }}
        run: cargo clippy -- -D warnings -D clippy::cast_possible_truncation

      - name: Clippy examples
        working-directory: examples
        if: ${{ steps.check_changes.outputs.crates_or_examples_changed == 'true' }}
        run: __CODEGEN_TARGET__="GPU-CLIPPY" RUSTC=rustc cargo clippy -- -D warnings -D clippy::cast_possible_truncation

      - name: Run tests
        working-directory: crates/rustc_codegen_gpu
        if: ${{ steps.check_changes.outputs.crates_changed == 'true' }}
        run: cargo test

      - name: Build
        working-directory: crates
        if: ${{ steps.check_changes.outputs.crates_or_examples_changed == 'true' }}
        run: cargo build --workspace

      - name: Run examples
        working-directory: examples
        if: ${{ steps.check_changes.outputs.crates_or_examples_changed == 'true' }}
        run: |
          cargo build
